# image: "python:3.7" 

# before_scripts:
#   - python3 -V
#   - pip install -r requirements.txt

# stages:
#   - test
#   - deploy

# test:
#   stage: test
#   script:
#     - python3 -V
#     - python3 test.py


# deploy:
#   stage: deploy
#   script:
#     - apt-get install curl -y

image: python:3.7

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - echo "Testing the app"
    - echo $CI_JOB_STAGE
    - python -V
    - python test.py

build:
  stage: build
  script: echo "Building the app"

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy the app"
    - sudo dpl --provider=heroku --app=cs242-assignment2 --api-key=$HEROKU_API_KEY
    # - git push heroku assignment-2.1:master
